// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// w2_distance
arma::mat w2_distance(const arma::mat& mu, const arma::mat& var, const arma::mat& mu2, const arma::mat& var2);
RcppExport SEXP _geneSetEmbedding_w2_distance(SEXP muSEXP, SEXP varSEXP, SEXP mu2SEXP, SEXP var2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var2(var2SEXP);
    rcpp_result_gen = Rcpp::wrap(w2_distance(mu, var, mu2, var2));
    return rcpp_result_gen;
END_RCPP
}
// sym_kl_distance
arma::mat sym_kl_distance(const arma::mat& mu, const arma::mat& var, const arma::mat& mu2, const arma::mat& var2);
RcppExport SEXP _geneSetEmbedding_sym_kl_distance(SEXP muSEXP, SEXP varSEXP, SEXP mu2SEXP, SEXP var2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var(varSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mu2(mu2SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type var2(var2SEXP);
    rcpp_result_gen = Rcpp::wrap(sym_kl_distance(mu, var, mu2, var2));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_enrichment_permutations
arma::mat rcpp_enrichment_permutations(const arma::mat& W, const arma::vec& stats, const int n_perm, const int seed);
RcppExport SEXP _geneSetEmbedding_rcpp_enrichment_permutations(SEXP WSEXP, SEXP statsSEXP, SEXP n_permSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_enrichment_permutations(W, stats, n_perm, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geneSetEmbedding_w2_distance", (DL_FUNC) &_geneSetEmbedding_w2_distance, 4},
    {"_geneSetEmbedding_sym_kl_distance", (DL_FUNC) &_geneSetEmbedding_sym_kl_distance, 4},
    {"_geneSetEmbedding_rcpp_enrichment_permutations", (DL_FUNC) &_geneSetEmbedding_rcpp_enrichment_permutations, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_geneSetEmbedding(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
